name: CI
on: [ push ]
jobs:
  build:
    name: Build & Lint

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache npm downloads
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: jgierer12/npm-auth-gpr@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GH_ELSEU_ALL }}

      # - name: Setup NPM Registry
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm config set @elseu:registry https://npm.pkg.github.com/

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Archive build artifacts
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  
  deploy_npm:
    name: Deploy on NPM
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    needs: [ build ]
    env:
      BRANCH: ${{ github.ref }}
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.4
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
